## Student Performance

The dataset is related to student performance and attributes in secondary education. Here's a general introduction based on the columns present in the DataFrame:

This dataset contains information about students in secondary education, including demographic details, family background, educational support, lifestyle choices, and academic performance. Each row represents a unique student, and the columns provide various attributes and characteristics associated with them.

Dataset contains following columns:
school: School attended by the student.
sex: Student's gender (male or female).
age: Student's age.
address: Type of address of the student (urban or rural).
famsize: Family size (binary categorization: "LE3" - less or equal to 3 or "GT3" - greater than 3).
Pstatus: Parent's cohabitation status (living together or apart).
Medu: Mother's education level (0 to 4, representing none to higher education).
Fedu: Father's education level (0 to 4, representing none to higher education).
Mjob: Mother's occupation.
Fjob: Father's occupation.
reason: Reason for choosing the school.
guardian: Student's guardian.
traveltime: Travel time to school.
studytime: Weekly study time (hours).
failures: Number of past class failures.
schoolsup: Extra educational support at school (yes or no).
famsup: Family educational support (yes or no).
paid: Extra paid classes within the course subject (yes or no).
activities: Extra-curricular activities (yes or no).
nursery: Attended nursery school (yes or no).
higher: Wants to take higher education (yes or no).
internet: Internet access at home (yes or no).
romantic: In a romantic relationship (yes or no).
famrel: Quality of family relationships (from 1 - very bad to 5 - excellent).
freetime: Free time after school (from 1 - very low to 5 - very high).
goout: Going out with friends (from 1 - very low to 5 - very high).
Dalc: Workday alcohol consumption (from 1 - very low to 5 - very high).
Walc: Weekend alcohol consumption (from 1 - very low to 5 - very high).
health: Current health status (from 1 - very bad to 5 - very good).
absences: Number of school absences.
G1: First period grade (from 0 to 20).
G2: Second period grade (from 0 to 20).
G3: Final grade (from 0 to 20).

In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt


import warnings
warnings.filterwarnings('ignore')

In [4]:
data = pd.read_csv("student-por.csv")
data

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,4,0,11,11
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,2,9,11,11
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,6,12,13,12
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,0,14,14,14
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,0,11,13,13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
644,MS,F,19,R,GT3,T,2,3,services,other,...,5,4,2,1,2,5,4,10,11,10
645,MS,F,18,U,LE3,T,3,1,teacher,services,...,4,3,4,1,1,1,4,15,15,16
646,MS,F,18,U,GT3,T,1,1,other,other,...,1,1,1,1,1,5,6,11,12,9
647,MS,M,17,U,LE3,T,3,1,services,services,...,2,4,5,3,4,2,6,10,10,10
648,MS,M,18,R,LE3,T,3,2,services,other,...,4,4,1,3,4,5,4,10,11,11

In [5]:
data.head(5)

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,4,0,11,11
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,2,9,11,11
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,6,12,13,12
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,0,14,14,14
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,0,11,13,13

In [6]:
data.tail(5)

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
644,MS,F,19,R,GT3,T,2,3,services,other,...,5,4,2,1,2,5,4,10,11,10
645,MS,F,18,U,LE3,T,3,1,teacher,services,...,4,3,4,1,1,1,4,15,15,16
646,MS,F,18,U,GT3,T,1,1,other,other,...,1,1,1,1,1,5,6,11,12,9
647,MS,M,17,U,LE3,T,3,1,services,services,...,2,4,5,3,4,2,6,10,10,10
648,MS,M,18,R,LE3,T,3,2,services,other,...,4,4,1,3,4,5,4,10,11,11

In [7]:
data.columns

Index(['school', 'sex', 'age', 'address', 'famsize', 'Pstatus', 'Medu', 'Fedu',
       'Mjob', 'Fjob', 'reason', 'guardian', 'traveltime', 'studytime',
       'failures', 'schoolsup', 'famsup', 'paid', 'activities', 'nursery',
       'higher', 'internet', 'romantic', 'famrel', 'freetime', 'goout', 'Dalc',
       'Walc', 'health', 'absences', 'G1', 'G2', 'G3'],
      dtype='object')